//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class code
    {
        public int id { get; set; }
        public System.DateTime tb_date { get; set; }
        public int tb_Basin { get; set; }
        public int tb_Block { get; set; }
        public int tb_Property { get; set; }
        public int tb_Building { get; set; }
        public string name_build { get; set; }
        public string Receiver { get; set; }
        public bool accept { get; set; }
        public Nullable<int> file_num { get; set; }
        public Nullable<System.DateTime> backtime { get; set; }
    }
}
