//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_WbayghaniEntities : DbContext
    {
        public DB_WbayghaniEntities()
            : base("name=DB_WbayghaniEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<code> code { get; set; }
        public virtual DbSet<namerole> namerole { get; set; }
        public virtual DbSet<rrole> rrole { get; set; }
        public virtual DbSet<table_login> table_login { get; set; }
    }
}
